
REVOKE EXECUTE ON FUNCTION public.generate_referral_code() FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.validate_recurring_fields() FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.validate_referral_status() FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.validate_scheduled_bill_fields() FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.validate_investment_history_fields() FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.validate_debt_fields() FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.validate_card_fields() FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.touch_detected_subscriptions() FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.set_waitlist_position() FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.validate_bank_connection_fields() FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.validate_bank_tx_type() FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.validate_prediction_alert_severity() FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.protect_gamification_fields() FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.prevent_plan_escalation() FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.validate_profile_type() FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.kora_memory_set_expires() FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.set_updated_at() FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.handle_new_user() FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.validate_whatsapp_message_direction() FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.delete_email(text, bigint) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.read_email_batch(text, integer, integer) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.move_to_dlq(text, text, bigint, jsonb) FROM PUBLIC;
